/* Gerado a partir de rules.py — motor de categorização para movimentos importados. */
const MERCHANT_MAP = {
 "CME CANIDELO": "Saúde e farmácia",
 "CEPI": "Saúde e farmácia",
 "BRIGHTGLOW": "Saúde e farmácia",
 "INTENSE HAND": "Saúde e farmácia",
 "OCCASION2SMILE": "Compras online",
 "IDIOTA": "Restauração e cafés",
 "ARCADIA": "Restauração e cafés",
 "SERRA ROXO": "Restauração e cafés",
 "SERRA & ROXO": "Restauração e cafés",
 "XOXO": "Restauração e cafés",
 "LETRARIA": "Restauração e cafés",
 "BOSCO": "Restauração e cafés",
 "EPICURA": "Restauração e cafés",
 "TETTRIS": "Restauração e cafés",
 "NINKI": "Restauração e cafés",
 "ANGULO MESTR": "Restauração e cafés",
 "CAPICCIA": "Restauração e cafés",
 "MANUEL RUI A": "Restauração e cafés",
 "NOMADAS": "Lazer e noite",
 "DONA MIRA": "Lazer e noite",
 "ROMANOFF": "Lazer e noite",
 "ERA UMA VEZ": "Lazer e noite",
 "FERRO BAR": "Lazer e noite",
 "MIRA JAZZ": "Lazer e noite",
 "FIASCO": "Lazer e noite",
 "PLANO B": "Lazer e noite",
 "CAE S. MAMEDE": "Lazer e noite",
 "MAKSU": "Transportes",
 "CARDAN": "Transportes",
 "UPMAX-GLOBAL": "Viagens",
 "MANTEIGARIA": "Restauração e cafés",
 "STARBUCKS": "Restauração e cafés",
 "OAKBERRY": "Restauração e cafés",
 "H3 ": "Restauração e cafés",
 "CELEIRO": "Supermercado",
 "PROZIS": "Desporto e ginásio",
 "SWAROVSKI": "Roupa e lojas",
 "PARFOIS": "Roupa e lojas",
 "LOVISA": "Roupa e lojas",
 "CHICCO": "Roupa e lojas",
 "TEA SHOP": "Roupa e lojas",
 "PULL BEAR": "Roupa e lojas",
 "PULL&BEAR": "Roupa e lojas",
 "GOTOGATE": "Viagens",
 "KIWI.COM": "Viagens",
 "DOUBLE TREE": "Viagens",
 "DOUBLETREE": "Viagens",
 "CORINTHIA": "Viagens",
 "PESTANA": "Viagens",
 "JACOBS INN": "Viagens",
 "MS* JACOBSINN": "Viagens",
 "MS JACOBSIN": "Viagens",
 "HBH DUBLIN": "Viagens",
 "TFL TRAVEL": "Transportes",
 "DT DUBLIN": "Transportes",
 "FLIXM": "Transportes",
 "FLIXBUS": "Transportes",
 "SONAR FESTIVAL": "Lazer e noite",
 "RESIDENT ADVIS": "Lazer e noite",
 "GUINNESS STO": "Lazer e noite",
 "GUINNESS SH": "Lazer e noite",
 "CLAUDE.AI": "Subscrições e digital",
 "GOOGLE ONE": "Subscrições e digital",
 "HELP.HBOMAX": "Subscrições e digital",
 "KINDLE": "Subscrições e digital",
 "HOTMART": "Subscrições e digital",
 "UPWORK": "Comissões e taxas",
 "REMOTEJOBS": "Subscrições e digital",
 "LUSITANIA": "Seguros",
 "MAPFRE": "Seguros",
 "MULTICARE": "Seguros",
 "ELEBE": "Restauração e cafés",
 "HERDADE MALH": "Restauração e cafés",
 "ESTACAO DAS CO": "Restauração e cafés",
 "FAROL IMAGIN": "Restauração e cafés",
 "TALHASCA": "Restauração e cafés",
 "MOMENTS LOUN": "Restauração e cafés",
 "MOMENTS CAFE": "Restauração e cafés",
 "CASA GUEDES": "Restauração e cafés",
 "CABANA DO PAST": "Restauração e cafés",
 "QUIMET": "Restauração e cafés",
 "OGHAM": "Restauração e cafés",
 "FRANKFURT": "Restauração e cafés",
 "TEMPLESUHI": "Restauração e cafés",
 "ORIGINE": "Restauração e cafés",
 "LEBILLET": "Lazer e noite",
 "TEELING": "Lazer e noite",
 "THE ROYAL COCK": "Lazer e noite",
 "ALAMEDA SHOP": "Roupa e lojas",
 "NORTHSPIRIT": "Outras compras",
 "ACPSENHORA": "Seguros",
 "CENTRO SOLDA": "Transportes",
 "PLANETA SIM": "Lazer e noite",
 "TEIXEIRA E MAR": "Restauração e cafés",
 "TEIXEIRA E M": "Restauração e cafés",
 "VERAO UTOPIC": "Lazer e noite",
 "SQ FOURTH": "Restauração e cafés",
 "SQ INDI": "Restauração e cafés",
 "EXUBERPINK": "Saúde e farmácia",
 "CORREIA BRESOL": "Restauração e cafés",
 "REGRAS IDENT": "Impostos e Estado",
 "OP BX VALOR": "Transportes",
 "BK1": "Restauração e cafés",
 "BK2": "Restauração e cafés",
 "PORTAROSSA": "Restauração e cafés",
 "BLACK PEPPER": "Restauração e cafés",
 "SAMMICH": "Restauração e cafés",
 "HOLY SANDWIC": "Restauração e cafés",
 "SNEAKY SIP": "Restauração e cafés",
 "STREET SMASH": "Restauração e cafés",
 "BROWNIE LOVERS": "Restauração e cafés",
 "TORANJA": "Restauração e cafés",
 "EUPAGO*TORANJA": "Restauração e cafés",
 "EL PATIO": "Restauração e cafés",
 "LOS CAZURROS": "Restauração e cafés",
 "ENTREPENAS": "Restauração e cafés",
 "ALDEANA": "Restauração e cafés",
 "COALLA": "Restauração e cafés",
 "MOLLY LEON": "Lazer e noite",
 "THE ACADEMY": "Lazer e noite",
 "WORLDS END": "Lazer e noite",
 "THE SOCIAL H": "Lazer e noite",
 "T CHAMPIONS": "Lazer e noite",
 "DISC RENDEZ": "Lazer e noite",
 "MONDO DISKO": "Lazer e noite",
 "LUXFRAGIL": "Lazer e noite",
 "EDDIES KLUB": "Lazer e noite",
 "BEER KINGDOM": "Lazer e noite",
 "CATEDRAL DE LE": "Lazer e noite",
 "RECOLETOS": "Lazer e noite",
 "FDN SANTA CA": "Lazer e noite",
 "FUNDACION": "Lazer e noite",
 "MIELE": "Roupa e lojas",
 "LUCIANO ARTE": "Roupa e lojas",
 "PERSONALIZ ART": "Roupa e lojas",
 "ESTANCO": "Outras compras",
 "TABACS": "Outras compras"
};
const KEYWORD_RULES = [
  ["Rendimentos", new RegExp("ORDENADOS|FORNECEDOR\\s*-","i")],
  ["Investimentos", new RegExp("\\bXTB\\b","i")],
  ["Renda", new RegExp("ordem permanente SEPA\\+ ?Jorge Pereira","i")],
  ["Impostos e Estado", new RegExp("Pag\\. ?DUC|AUTORIDADE TRIBUT|\\bIMPOSTO\\b|SEG\\.? SOCIAL|\\bUKVI\\b|\\bETA\\b MOB|FINANCAS","i")],
  ["Seguros", new RegExp("SEGUROS|LUSITANIA|MAPFRE|MULTICARE|FIDELIDADE|ALLIANZ|TRANQUILIDADE|AGEAS","i")],
  ["Contas da casa", new RegExp("AGUAS|GOLD ENERG|NOS COMUNI|\\bEDP\\b|GALP ENERGIA|ALTICE|\\bMEO\\b|VODAFONE|\\bDIGI\\b|IBERDROLA|ENDESA|CONDOMINIO","i")],
  ["Comissões e taxas", new RegExp("Comiss(ã|a)o|COMISS|Imposto do selo|MANUTEN(Ç|C)|ANUIDADE","i")],
  ["Levantamentos", new RegExp("^LEVANT|LEVANTAMENTO|^LEV ","i")],
  ["Supermercado", new RegExp("CONTINENTE|PINGO ?DOCE|\\bA SUPER\\b|INTERMARCHE|ALIADOS SUPERM|\\bLIDL\\b|MINIPRECO|AUCHAN|MERCADONA|SUPERMERC|FROIZ|\\bSPAR\\b|MEU SUPER|\\bDIA\\b|CELEIRO|MERCEARIA|TALHO|PEIXARIA|LOCAL PANTRY|A S FREIXO|A\\.?S\\.? SANTO TIR|A S AD MIA","i")],
  ["Transportes", new RegExp("UBER\\s*\\*?\\s*(TRI|BUSINE|ONE)|UBER TRIP|\\bUBER\\b|\\bUBR\\*|BOLT\\.EU|BOLT\\.EUO|FREE ?NOW|\\bTAXI\\b|CABIFY|\\bRNE\\b|REDE NAC|REDE EXPRESS|COMBOIOS|\\bCP\\b|FLIXBUS|FLIXM|ALSA|RENFE|METRO |METROPOLITANO|STCP|CARRIS|TRANSDEV|\\bTFL\\b|\\bMTA\\b|^A\\d{1,2}\\b|PORTAGEM|VIA ?VERDE|BRISA|ASCENDI|GALP\\b|\\bBP\\b|REPSOL|PRIO |CEPSA|CEDIPSA|MOEVE|PETRO|POSTO |ABASTEC|GARAGEM|PARQUE|PARKIN|ESTACION|ESTAC |EMEL|TMP |TFGEST|SABA |EMPARK|MAKSU|^PA [A-Z]|AEROP|AEROPORTO|EA AER|TRANSATEL|MILSERVICE E|CARDAN|OFICINA|PNEUS|INSPE(C|Ç)","i")],
  ["Viagens", new RegExp("BOOKING|BKG\\*|AIRBNB|RYANAIR|EASYJET|VUELING|WIZZ|IBERIA|LUFTHANSA|BRITISH AIR|\\bTAP\\b|GOTOGATE|KIWI\\.COM|EDREAMS|OPODO|SKYSCANNER|EXPEDIA|FLIGHTS ON|PARTNERS ON BO|HOSTEL|\\bHOTEL\\b|POUSADA|GUEST ?HOUSE|RESIDENCIAL|PESTANA|CORINTHIA|DOUBLE ?TREE|MELIA|NH \\b|IBIS\\b|DUTY ?FRE|DFS|AVOLTA|WH SMITH|HMS HOST|UPMAX|JACOBS ?INN|HbH |M OU CO HOTE","i")],
  ["Subscrições e digital", new RegExp("GOOGLE\\*|GOOGLE PLAY|GOOGLE ONE|ANTHROPIC|CLAUDE\\.AI|OPENAI|CHATGPT|NETFLIX|SPOTIFY|HBO|HBOMAX|DISNEY|PRIME VID|AMAZON PRIME|HAYSTACK|APPLE\\.COM|ICLOUD|YOUTUBE|PATREON|CURSOR|GITHUB|NINTENDO|PLAYSTATION|STEAM|CRUNCHYROLL|VERSAO DIARI|VRSAO DIARIA|KINDLE|AUDIBLE|CANVA|NOTION|DROPBOX|ADOBE|MICROSOFT|LINKEDIN|HOTMART|REMOTEJOBS|SUBSCRI","i")],
  ["Desporto e ginásio", new RegExp("VIVAGYM|SQ ?\\*?ADVANCED|\\bGYM\\b|GINASIO|FITNESS|PADEL|CROSSFIT|PISCINA|CLIMBING|UPACLIMB|DECATHLON|SPORT ZONE|PROZIS|MYPROTEIN","i")],
  ["Saúde e farmácia", new RegExp("FARMACIA|PARAFARM|\\bFARM\\b|CLINICA|CENTRO MEDICO|\\bCME\\b|HOSPITAL|DENTIST|DENTAR|MEDIC|ANALISES|LABORATORIO|OPTICA|MULTIOPTICAS|WELL ?S\\b|CABELEIREIR|BARBEAR|BARBER|MANICURE|INTENSE HAND|ESTETICA|\\bSPA\\b|MASSAG|CEPI\\b|BRIGHTGLOW","i")],
  ["Animais", new RegExp("ZOOPLUS|PETLANDIA|\\bPET\\b|PETSHOP|VETERIN|\\bVET\\b|GENEROSIDADE|ANIMAL","i")],
  ["Compras online", new RegExp("AMAZON|\\bAMZN\\b|TEMU|VINTED|MGP\\*|ALIEXPRESS|\\bEBAY\\b|SHEIN|\\bETSY\\b|WISH\\.COM|HIPAY|HTTPS HIPA|WORTEN\\.PT|FNAC\\.PT|OCCASION2SMILE|DSTORE","i")],
  ["Roupa e lojas", new RegExp("\\bZARA\\b|ZARA\\.COM|ZARAPORTO|DRUNI|\\bNYX\\b|MILSERVI|BERSHKA|PULL ?&? ?BEAR|STRADIVARIUS|\\bMANGO\\b|\\bH&M\\b|\\bHM PT|PRIMARK|LEROY MERLIN|\\bIKEA\\b|\\bFNAC\\b|WORTEN|EL CORTE|\\bNORMAL\\b|FLYING TIGER|RITUALS|SEPHORA|PERFUM|SWAROVSKI|PARFOIS|LOVISA|CHICCO|TEA SHOP|COSMETIC|PLURICOSMET|AROMAS PRECIOS|LIVRARIA|BERTRAND|FLORISTA|OURIVES|JOALHAR","i")],
  ["Lazer e noite", new RegExp("CINEMA|CINEMAS NOS|NOS ALAMEDA|\\bIMAX\\b|TEATRO|MUSEU|MUSEUM|GALERIA|EXPO|DISCOTECA|\\bDISC\\b|\\bCLUB\\b|\\bKLUB\\b|NIGHTCLUB|SHOTGUN|DICE\\.FM|TICKETLINE|TICKET ?LINE|TICKETS|ENTERTICKET|3CKET|\\bBOL\\b|BOL\\.PT|FEVER|SONAR|FESTIVAL|CONCERT|LIVE |RESIDENT ADVIS|\\bPUB\\b|\\bBAR\\b|TABERNA|CERVEJARIA|BREWERY|GUINNESS|TATTOO|KARAOKE|BOWLING|ESTADIO|PLANO B|FERRO BAR|MIRA JAZZ|FIASCO|NOMADAS|DONA MIRA|ROMANOFF|ERA UMA VEZ|CAE S\\. MAMEDE|UNDERGROUND|GARE |LUXFRAGIL|MONDO DISKO|EDDIES|CATEDRAL|RECOLETOS|FDN SANTA CA|FUNDACION","i")],
  ["Restauração e cafés", new RegExp("RESTAUR|\\bREST|\\bCAFE|CAFÉ|CAFETERIA|SNACK|PASTELARIA|PASTEIS|PADARIA|CONFEITARIA|MANTEIGARIA|GELAT|BRUNCH|BISTRO|TASCA|TASQUINHA|TASCO|CHURRAS|MARISQ|PIZZ|BURGER|SUSHI|RAMEN|POKE|KEBAB|TAPAS|TAPERIA|GRILL|\\bFOOD\\b|EATS|HUNGRY|QUIOSQUE|KIOSK|STARBUCKS|OAKBERRY|ACAI|BREW|COFFEE|BAKERY|SANDWIC|CREPE|DOCE|BROWNIE|BLOOM|AREAS PORTUGAL|BRISA AREAS|IDIOTA|ARCADIA|XOXO|LETRARIA|BOSCO|EPICURA|TETTRIS|NINKI|ANGULO MESTR|CAPICCIA|SERRA ?&? ?ROXO|MANUEL RUI A|H3 |MESA \\d|VENDING|MAQ\\. |TOPVENDING|CITYVENDING|DECORUM VENDIN","i")],
  ["Transferências recebidas", new RegExp("^IPS\/|^TRANSF SEPA|^TRF |^Trf ","i")],
  ["Transferências enviadas", new RegExp("^Trf imediata|^Trf MB WAY|^TRF MBW|^TRF ENV|^Trf |MBWAY|MB WAY|^TRANSFER(Ê|E)NCIA|^TRANSF SEPA","i")],
];
const CAT_SIGN = {"Transferências recebidas": "+", "Transferências enviadas": "-", "Levantamentos": "-"};
const CITY_RE = /(PORTO|COIMBRA|BRAGA|LISBOA|LISBON|MATOSINHOS|GAIA|AVEIRO|GUIMARAES|VIANA|LEIRIA|CASCAIS|SINTRA|FARO|BARCELONA|MADRID|LONDON|DUBLIN|LEON|VIGO|MAIA)\s*$/i;
function merchantOf(desc){
  let m = String(desc||"").replace(/^(COMPRA|LEVANT)\s+/,"");
  m = m.replace(/\s*0(561746|183372)(\/\d+)?\s*/g," ");
  m = m.replace(/\s+FINAL BALANCE.*$/i,"");
  return m.replace(/\s{2,}/g," ").trim();
}
const cleanName = m => m.replace(CITY_RE,"").trim();
function autoCategorize(desc, amount){
  const sign = amount>0 ? "+" : "-";
  const m = merchantOf(desc), c = cleanName(m);
  const lc = c.toLowerCase(), lm = m.toLowerCase();
  for(const key in MERCHANT_MAP){
    const k = key.toLowerCase(), cat = MERCHANT_MAP[key];
    if(lc.startsWith(k) || lm.startsWith(k) || lc.includes(k)){
      if((CAT_SIGN[cat]||sign) === sign) return cat;
    }
  }
  for(const [cat, rx] of KEYWORD_RULES){
    if(CAT_SIGN[cat] && CAT_SIGN[cat] !== sign) continue;
    if(rx.test(desc) || rx.test(c)) return cat;
  }
  if(sign === "+") return "Rendimentos";
  return /^COMPRA/.test(desc) ? "Outras compras" : "Outros";
}